---
title: "GRD 610A Data Visualization II"
subtitle: "Homework #2"
author: "Jenn Schilling"
date: "2021-02-21"
output:
 html_document:
  theme: "simplex" # Theme Gallery: https://www.datadreaming.org/post/r-markdown-theme-gallery/
---


```{r setup, include=FALSE}

## By default, show code for all chunks in the knitted document,
## as well as the output. To override for a particular chunk
## use echo = FALSE in its options.
knitr::opts_chunk$set(echo = TRUE)

## Set the default size of figures
knitr::opts_chunk$set(fig.width=8, fig.height=5)  

## Load the libraries you will be using 
library(here)
library(tidyverse)

## Load the dataset you will be using
library(palmerpenguins)

```



# Homework Assignment

This is where you will put your R code and create your plots. Remember to comment your code.

```{r explore-data}

View(penguins)

summary(penguins)

table(penguins$species)

table(penguins$island)

table(penguins$year)

```


```{r first-plot}

summary_data <- penguins %>%
  group_by(species, island) %>%
  summarise(total = n(),
            .groups = "keep")

p1 <- ggplot(data = summary_data,
            mapping = aes(x = species,
                          y = total,
                          fill = species))

p1 + 
  geom_col() +
  facet_wrap(~island)


```

```{r second-plot}

avg_data <- penguins %>%
  group_by(species) %>%
  summarise(avg_bill_length = mean(bill_length_mm, na.rm = TRUE), # na.rm needs to be TRUE to remove missing values and properly compute the average
            avg_bill_depth = mean(bill_depth_mm, na.rm = TRUE),
            .groups = "keep")

p2 <- ggplot(data = avg_data,
             mapping = aes(x = avg_bill_length,
                           y = avg_bill_depth,
                           color = species))

p2 + 
  geom_point()


```

```{r third-plot}

compute_data <- penguins %>%
  mutate(bill_length_depth = bill_length_mm * bill_depth_mm)

p3 <- ggplot(data = compute_data,
             mapping = aes(x = bill_length_depth,
                           y = body_mass_g,
                           color = species))

p3 + 
  geom_point() +
  geom_smooth(se = FALSE)

```

